version: '3.1'

services:
  spring-jwt-mariadb:
    image: mariadb:10.7
    restart: 'always'
    container_name: drive_maria_db
    volumes:
      - /var/lib/docker/volumes/spring-jwt/mariadb:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: qaz123
      MYSQL_DATABASE: jwt
      MYSQL_USER: jwt
      MYSQL_PASSWORD: qaz123
    command: mysqld --default-authentication-plugin=mysql_native_password
    ports:
      - "3306:3306"
    networks:
      - spring-jwt-network

networks:
  spring-jwt-network: